### ISSUE TITLE
Can't set ipadress!!

### ISSUE THREAD

**Issue by Neko-vecter** [221robotics/RobotOpen-HA-Library#2]
I can't set ip
Here is the code
  RobotOpen.setIP(IPAddress(192, 168, 1, 23));
  RobotOpen.setSubnet(IPAddress(255,255,255,0));
  RobotOpen.setGateway(IPAddress(192, 168, 1, 1));

**Comment by ajlapp** [comment]
Your syntax is incorrect...

That said, I tested the method shown in the Docs and also received an error.  I'll have to review this in more detail.

Try this:

1 . At the top of your program:
IPAddress ip(192, 168, 0, 23);
IPAddress gateway(192, 168, 0, 1);
IPAddress subnet(255, 255, 255, 0);

2.  In setup()
RobotOpen.setIP(ip);
RobotOpen.setGateway(gateway);
RobotOpen.setSubnet(subnet);
